spring:
  application:
    name: dubbo-consumer
server:
  port: 9001


dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 5000